name: Téléchargement et analyse des règlements d'urbanisme

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install -e .
        sudo apt-get install poppler-utils
    - name: Cache downloads
      id: cache-downloads
      uses: actions/cache@v4
      with:
        path: download
        key: reglements-urbanisme
    - name: Download
      run: sh scripts/download.sh
    - name: Extract
      run: sh scripts/extract.sh
    - name: Index
      run: sh scripts/index.sh
    - name: Setup Pages
      uses: actions/configure-pages@v5
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: export/
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
