name: Téléchargement et analyse des règlements d'urbanisme

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

# Install much smaller CPU version of PyTorch
env:
  PIP_INDEX_URL: https://download.pytorch.org/whl/cpu
  PIP_EXTRA_INDEX_URL: https://pypi.org/simple/

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install -e .
    - name: Cache downloads
      id: cache-downloads
      uses: actions/cache@v4
      with:
        path: download/*.pdf
        key: reglements-urbanisme
    - name: Download
      run: |
        alexi -v download --exclude=Plan --exclude=/derogation \
                 --exclude='\d-[aA]dopt' --exclude='Z-\d' \
                 --exclude='-[rR]eso'
        for d in download/*.pdf; do
            bn=$(basename $d .pdf)
            for dd in data/train data/dev data/test; do
                if [ -e "${dd}/${bn}.csv" ]; then
                    cp "${dd}/${bn}.csv" download/
                fi
            done
        done
        alexi -v download -u https://vsadm.ca/citoyens/reglementation/reglementation-durbanisme/ -o download/vsadm --all-pdf-links
        alexi -v download -u https://www.vss.ca/services-aux-citoyens/services/reglementation-durbanisme/ \
              -o download/vss --all-pdf-links -x '[Aa]nnexe'
    - name: Extract
      run: |
        alexi -v extract -m download/index.json download/*.pdf
        alexi -v extract -m download/vsadm/index.json -o export/vsadm download/vsadm/*.pdf
        alexi -v extract -m download/vss/index.json -o export/vss download/vss/*.pdf
    - name: Index
      run: |
        alexi -v index -o export/_idx export
        alexi -v index -o export/vsadm/_idx export/vsadm
        alexi -v index -o export/vss/_idx export/vss
    - name: Setup Pages
      uses: actions/configure-pages@v5
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: export/
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
