name: Entraînement et évaluation des modèles CRF

on:
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install
      run: |
        python3 -m pip install hatch
    - name: Cross-validate
      run: |
        hatch run -- sh results/run.sh
    - name: Upload results
      uses: actions/upload-artifact@v4
      with:
        name: results
        path: results/*.csv
    - name: Train
      run: |
        hatch run train
    - name: Upload models
      uses: actions/upload-artifact@v4
      with:
        name: models
        path: alexi/models/
